Fix missing kcm dependency for runcommand module
Without it, the build may fail with:

fatal error: kcmutils_version.h: No such file or directory
   35 | #include <kcmutils_version.h>
      |          ^~~~~~~~~~~~~~~~~~~~