CMake: Set required C++ standard to C++20
This fixes the following compiler error with winrt headers using mingw-w64 gcc toolchain.

In file included from winrt/Windows.Foundation.h:12,
                 from kdeconnect-kde/plugins/sendnotifications/windowsnotificationslistener.h:11,
                 from kdeconnect-kde/plugins/sendnotifications/sendnotificationsplugin.cpp:12:
winrt/base.h:89:2: error: #error C++/WinRT requires coroutine support, which is currently missing. Try enabling C++20 in your compiler.
   89 | #error C++/WinRT requires coroutine support, which is currently missing. Try enabling C++20 in your compiler.
      |  ^~~~~